# Generated by Django 5.0.6 on 2024-05-20 13:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_lname', models.CharField(max_length=500)),
                ('patient_fname', models.CharField(max_length=500)),
                ('age', models.CharField(max_length=3)),
                ('specimen_choice', models.CharField(choices=[('type1', 'Blood'), ('type2', 'Stool'), ('type3', 'Urine'), ('type4', 'Saliva')], max_length=2000)),
                ('specimen_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('test_type', models.CharField(blank=True, max_length=4000, null=True)),
                ('pathologist_present', models.CharField(max_length=500)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('date_released', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
