# Generated by Django 5.0.6 on 2024-05-20 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='date_e',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='time_e',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='test_type',
            field=models.CharField(blank=True, choices=[('test1', 'CBC'), ('test2', 'BMP'), ('test3', 'BSL'), ('test4', 'Leukocytes'), ('test5', 'Occult blood'), ('test6', 'fat'), ('test7', 'RBC urine'), ('test8', 'Glucose urine'), ('test9', 'Protein urine'), ('test10', 'HIV'), ('test11', 'Hypogonadism'), ('test12', 'Cushing')], max_length=4000, null=True),
        ),
    ]
