# Generated by Django 5.0.6 on 2024-05-27 15:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim', '0004_rename_pathologist_present_patient_referring_doctor_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='collected_by',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='specimen_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='collected_by',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='specimen_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name='patient',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('enabled', 'Enabled'), ('processing', 'Processing'), ('complete', 'Complete')], max_length=3000, null=True),
        ),
    ]
