# Generated by Django 5.0.6 on 2024-05-27 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lim', '0005_remove_patient_collected_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sample',
            old_name='specimen_id',
            new_name='sample_id',
        ),
        migrations.AddField(
            model_name='sample',
            name='collection_time',
            field=models.DateTimeField(null=True),
        ),
        migrations.AddField(
            model_name='sample',
            name='status',
            field=models.CharField(choices=[('not_paid', 'Not Paid'), ('enabled', 'Enabled'), ('processing', 'Processing'), ('complete', 'Complete')], max_length=500, null=True),
        ),
    ]
